name: Run YouTube AI Test

on:
  workflow_dispatch: # This adds a manual "Run workflow" click button to your GitHub interface

jobs:
  run-ai-pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: python main.py
